name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up MSVC (x64)
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Download icon
        run: curl -L -o res/factorio.ico https://github.com/marnason/factorio-icon/releases/latest/download/factorio.ico

      - name: Build
        run: |
          mkdir build
          rc /nologo /fo "build\app.res" "res\app.rc"
          cl /nologo /O2 /W4 /MT /Fe:"build\factorio-icon-launcher.exe" "src\main.c" "build\app.res" /link /SUBSYSTEM:WINDOWS user32.lib shell32.lib

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/factorio-icon-launcher.exe
            UNLICENSE
